ack:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_rwh_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_lwh_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_rw_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_rotate
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}

  joint_lw_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_rotate
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}




